### ISSUE TITLE
README Lacks Usage Details

### ISSUE THREAD

**Issue by DarioS** [wwylab/DeMix#3]
For example, how to install the software is not explained. It's not in CRAN nor in Bioconductor, so giving an example of how to use `devtools:::install_github` is important. Also, I don't know how to install the dependencies automatically like `install.packages` automatically does for CRAN-hosted packages.

```
> devtools:::install_github("wwylab/DeMix")
Downloading GitHub repo wwylab/DeMix@master
from URL https://api.github.com/repos/wwylab/DeMix/zipball/master
Installing DeMix
'/path/to/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpglFPYR/devtools28e47ef9e077/wwylab-DeMix-4be1c5e'  \
  --library='/path/to/Rpackages' --install-tests 

ERROR: dependency ‘DSS’ is not available for package ‘DeMix’
* removing ‘/path/to/Rpackages’
Error: Command failed (1)
```

Also, there are three DeMixT functions. How should the user choose which one to use? Guidance would be valuable.

**Comment by wwylab** [comment]
The linked package DSS should be installed prior to the installation of DeMix. We already included an instruction of installation to the Readme (the homepage). We are still studying how to incorporate linked packages automatically in installation.

The DeMixT function is what you should use if you want to implement the whole deconvolution process. Our deconvolution includes two stages (please refer to our DeMix/DeMixT paper). DeMixT.S1 implements the first stage, while DeMixT.S2 implements the second stage. DeMixT sequentially calls these two functions to finish the whole process.
